image: Visual Studio 2022
version: 1.0.{build}

build_script:
  - dotnet restore -v quiet
  - ps: dotnet build /p:configuration=Release /p:Version=$($env:appveyor_build_version)

test: off

artifacts:
  - path: src\**\bin\release\*.nupkg
    name: NuGet package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: TCK4iz4NnVAK6iAZbpocgig7CBxDTywbtFXcj61NfCr2aEHkT1mPuSj7/yLEkkp9
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/
